kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - tag
    - pull_request

steps:
  - name: fmt and tidy
    image: somethingbot/golang:1.18
    commands:
      - test -z $(go fmt ./...)
      - go mod tidy
      - git diff --exit-code -- go.mod go.sum
      - git diff --exit-code -- go.mod go.sum > test -z
  - name: generate-check
    image: somethingbot/golang:1.18
    commands:
      - go generate
      - git diff
      - test -z "$(git diff-index --name-only HEAD --)"
  - name: build and vet
    image: somethingbot/golang:1.18
    commands:
      - go build .
      - go vet -race -v ./...
  - name: test
    image: somethingbot/golang:1.18
    commands:
      - go test -v ./... -short
---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - tag

depends_on:
  - build

steps:
  - name: test-integration
    image: somethingbot/golang:1.18
    commands:
      - go test -v ./...
    environment:
      discordapikey:
        from_secret: discordapikey