kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - tag
    - pull_request

steps:
  - name: fmt and tidy
    image: golang:1.18
    commands:
      - test -z $(go fmt ./...)
      - go mod tidy
      - git diff --exit-code -- go.mod go.sum
      - git diff --exit-code -- go.mod go.sum > test -z
  - name: build and vet
    image: golang:1.18
    commands:
      - go build .
      - go vet -race -v ./...
  - name: test
    image: golang:1.18
    commands:
      - go test -v ./... -short
---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - tag

depends_on:
  - build

steps:
  - name: test-integration
    image: golang:1.18
    commands:
      - go test -v ./...
    environment:
      discordapikey:
        from_secret: discordapikey
---
kind: pipeline
type: docker
name: tagged version in libinfo

trigger:
  event:
    - push

#depends_on:
#  - build

steps:
  - name: check version
    image: golang:1.18
    commands:
      - ls -lha
      - export LATEST_TAG=$(git tag --sort=committerdate | tail -1)
      - echo $LATEST_TAG
      - export LATEST_TAG_WITHOUT_PARENTHESES=$(git tag --sort=committerdate | tail -1 | awk '{print substr($0,2, length($0))}')
      - echo $LATEST_TAG_WITHOUT_PARENTHESES
      - export TAG_AT_HEAD=$(git tag --points-at HEAD)
      - echo $TAG_AT_HEAD
      - export LIBINFO_VERSION=$(grep "BotLibraryVersion =" discord/libinfo/info.go | awk '{print substr($3, 2, length($3)-2)}')
      - echo $LIBINFO_VERSION
      - echo Current latest tag is $LATEST_TAG HEAD is $TAG_AT_HEAD
      - echo Current tag in discord/libinfo/info.go is $LIBINFO_VERSION
      - test $LIBINFO_VERSION = $LATEST_TAG_WITHOUT_PARENTHESES